import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Fedd from '../components/Fedd'
import Modal from '../components/Modal'



export default function Home() {
  return (
    <div className=' bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://w7.pngwing.com/pngs/815/101/png-transparent-www-mevrouwpak-nl-advertising-graphic-design-instagram-instagram-logo-business-advertising-thumbnail.png" />
      </Head>
      <Header/>
      <Fedd/>
      <Modal/>
    </div>
  )
}
